[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["bdnd"]

[tool.setuptools.package-data]
"*" = ["*.md", "*.txt"]

